services:
  redis1:
      image: "redis:latest"
      container_name: "redis-server-1"
      ports:
        - "6379:6379"
      command: redis-server --databases 2  # Configures Redis to use 2 databases
      restart: always

  redis2:
      image: "redis:latest"
      container_name: "redis-server-2"
      ports:
        - "6380:6379"  # Maps to a different port for the second Redis instance
      command: redis-server --databases 2  # Configures Redis to use 2 databases
      restart: always
      
  python-dns:
    build: .
    container_name: "python-dns-resolver"
    ports:
      - "1053:1053"
    environment:
      - REDIS_HOST1=redis1
      - REDIS_HOST2=REDIS_HOST2
    depends_on:
      - redis1
      - redis2
    restart: always
